# Generated by Django 5.2.8 on 2025-12-04 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_censorinfo_movieinfo_censor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movieinfo',
            old_name='censor',
            new_name='censor_details',
        ),
        migrations.AddField(
            model_name='movieinfo',
            name='directed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directed_movies', to='movies.directors'),
        ),
    ]
