# Generated by Django 5.2.7 on 2025-12-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_censorinfo_movieinfo_censor_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieinfo',
            name='censor_details',
        ),
        migrations.AddField(
            model_name='movieinfo',
            name='poster',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.DeleteModel(
            name='CensorInfo',
        ),
    ]
