# Generated by Django 5.2.8 on 2025-12-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_rename_censor_movieinfo_censor_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieinfo',
            name='actors',
            field=models.ManyToManyField(related_name='acted_movies', to='movies.actors'),
        ),
    ]
